27April18-ck-project-Eve/ck-project/Controllers/LogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;



using System.Data.SqlClient;

using PagedList.Mvc;

namespace ck_project.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class LogController : Controller
    {
        // GET: Log
        ckdatabase db = new ckdatabase();
        static List<tax> lst = new List<tax>();
        static List<rate> ratelst = new List<rate>();
        //string Emp = null, 

        /*    
              public ActionResult StateTax()
              {

                  try
                  {

                      var state = new List<SelectListItem>
                      {
                          //  new SelectListItem() { Text = "WV", Selected = true, Value = "" }
                      };
                      state.AddRange(db.taxes.Where(CCVV => CCVV.state != null).Select(b => new SelectListItem

                      {
                          Text = b.state,
                          Selected = true,
                          Value = b.state.ToString()
                      }).Distinct());
                      ViewBag.state = state;

                      var result = db.taxes.Where(l => ((l.state=="Type") && l.tax_anme == "State Tax")).ToList(); 
                      //LogController.lst = result;
                      return View();

                      //return View(db.leads.Where(x => (x.project_name.Contains(search) || search == null) && x.project_status_number == type && (x.project_status_number != 6 && x.deleted == false)).ToList());
                  }
                  catch (Exception e)
                  {
                      ViewBag.m = "Something went wrong ... " + e.Message;
                      return View();
                  }
              }

              
            */

        /*    public ActionResult StateTax(int? page, string search = null, string Type = null, string Start = null, string end = null, string msg = null)
            {


                DateTime start = string.IsNullOrEmpty(Start) ? DateTime.MinValue : DateTime.Parse(Start);
                DateTime end2 = string.IsNullOrEmpty(end) ? DateTime.MaxValue : DateTime.Parse(end);
                TimeSpan ts = new TimeSpan(23, 59, 59);
                end2 = end2.Date + ts;


                try
                {
                    ViewBag.m = msg;
                    var ClassInfo = new List<SelectListItem>();

                    ClassInfo.AddRange(db.taxes.Where(CCVV => CCVV.state != null).Select(b => new SelectListItem

                    {
                        Text = b.state,
                        Selected = true,
                        Value = b.state.ToString()
                    }).Distinct());
                    ViewBag.lead_type = ClassInfo;




                    var result = db.taxes.Where(l => (l.state == Type)  && l.tax_anme == "State Tax" ).ToList();
                    //LogController.lst = result;

                //   return View(result.ToPagedList(page ?? 1, 8));

                    return View(db.leads.Where(x => (x.project_name.Contains(search) || search == null) && x.project_status_number == type && (x.project_status_number != 6 && x.deleted == false)).ToList());
                }
                catch (Exception e)
                {
                    ViewBag.m = "Something went wrong ... " + e.Message;
                    return View();
                }
            }




    */
    /*
        public ActionResult StateTax(FormCollection form)
        {
            try
            {
                //setting dropdown list for forgern key
                var state = new List<SelectListItem>();
                state.AddRange(db.taxes.Where(x => x.state != null).Select(a => new SelectListItem
                {
                    Text = a.state,
                    Selected = false,
                    Value = a.state.ToString()
                }).Distinct());

                //setting variable passing
                ViewBag.state = state;

                //create instance
                tax target = new tax();
                //get property
                TryUpdateModel(target, new string[] { "tax_value", "tax_anme", "city", "state", "county", "zipcode", "end_date", "tax_number", "start_date" }, form.ToValueProvider());

                //validate
                //  double tempPhoneNumber = 0;
                ViewBag.Error = null;


                {
                    target.tax_anme = "State Tax";
                    target.city = "";
                    target.county = "";
                    target.zipcode = "";

                    target.start_date = System.DateTime.Now;
                    target.end_date = System.DateTime.Now;

                    db.taxes.Add(target);
                    db.SaveChanges();
                    ViewBag.m = "Tax was successfully updated " + "on " + System.DateTime.Now;
                }
                return View();




            }


            catch (Exception e)
            {
                ViewBag.m = "The customer was not created ... " + e.Message;
                return View();
            }
        }

*/
       


            public ActionResult StateTax(FormCollection form)
        {

            try
            {
                //setting dropdown list for forgern key
                var state = new List<SelectListItem>();
                state.AddRange(db.taxes.Where(x => x.state != null).Select(a => new SelectListItem
                {
                    Text = a.state,
                    Selected = false,
                    Value = a.state.ToString()
                }).Distinct());

                //setting variable passing
                ViewBag.state = state;
              
                //create instance
                tax target = new tax();
                //get property
                TryUpdateModel(target, new string[] { "tax_value", "tax_anme", "city", "state", "county", "zipcode", "end_date", "tax_number", "start_date" }, form.ToValueProvider());

                //validate
                //  double tempPhoneNumber = 0;
                ViewBag.Error = null;

                
                {
                    target.tax_anme = "State Tax";
                    target.city = "";
                    target.county = "";
                    target.zipcode = "";
                    
                    target.start_date = System.DateTime.Now;
                    target.end_date = System.DateTime.Now;

                    db.taxes.Add(target);
                    db.SaveChanges();
                    ViewBag.m = "Tax was successfully updated " + "on " + System.DateTime.Now;
                }
                return View();




            }
                  

                catch (Exception e)
                {
                    ViewBag.m = "The Tax was not created ... " + e.Message;
                    return View();
                }

           

        }





        public ActionResult StateTax(int? page, string search = null, string Type = null, string Type1 = null, string Start = null, string end = null, string msg = null)
        {


            DateTime start = string.IsNullOrEmpty(Start) ? DateTime.MinValue : DateTime.Parse(Start);
            DateTime end2 = string.IsNullOrEmpty(end) ? DateTime.MaxValue : DateTime.Parse(end);
            TimeSpan ts = new TimeSpan(23, 59, 59);
            end2 = end2.Date + ts;


            try
            {
                ViewBag.m = msg;
                var ClassInfo = new List<SelectListItem>
                {
                      new SelectListItem() { Text = "Select State", Selected = true, Value = "" }
                };
                ClassInfo.AddRange(db.taxes.Where(CCVV => CCVV.state != null).Select(b => new SelectListItem

                {
                    Text = b.state,
                    Selected = false,
                    Value = b.state.ToString()
                }).Distinct());
                ViewBag.lead_type = ClassInfo;




                var result = db.taxes.Where(l => (l.state == Type) && (l.tax_anme == "State Tax") && l.state == Type).ToList();


                LogController.lst = result;

                return View(result.ToPagedList(page ?? 1, 8));

                //return View(db.leads.Where(x => (x.project_name.Contains(search) || search == null) && x.project_status_number == type && (x.project_status_number != 6 && x.deleted == false)).ToList());
            }
            catch (Exception e)
            {
                ViewBag.m = "Something went wrong ... " + e.Message;
                return View();
            }
        }


        public ActionResult CountyTax(int? page, string search = null, string Type = null, string Type1 = null, string Start = null, string end = null, string msg = null)
        {


            DateTime start = string.IsNullOrEmpty(Start) ? DateTime.MinValue : DateTime.Parse(Start);
            DateTime end2 = string.IsNullOrEmpty(end) ? DateTime.MaxValue : DateTime.Parse(end);
            TimeSpan ts = new TimeSpan(23, 59, 59);
            end2 = end2.Date + ts;


            try
            {
                ViewBag.m = msg;
                var ClassInfo = new List<SelectListItem>
                {
                      new SelectListItem() { Text = "Select State", Selected = true, Value = "" }
                };
                ClassInfo.AddRange(db.taxes.Where(CCVV => CCVV.state != null).Select(b => new SelectListItem

                {
                    Text = b.state,
                    Selected = false,
                    Value = b.state.ToString()
                }).Distinct());
                ViewBag.lead_type = ClassInfo;



                var ClassInfo1 = new List<SelectListItem>
                {
                      new SelectListItem() { Text = "Select County", Selected = true, Value = "" }
                };

27April18-ck-project-Eve/ck-project/Views/Log/BOTax.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<ck_project.tax>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @if (ViewBag.m != null)
    {
        <script type="text/javascript">
 $(document).ready(function () {
     toastr.success('@ViewBag.m');
     @ViewBag.m = null
 });

        </script>
    }
}
@{
    if (HttpContext.Current.User.IsInRole("Administrator"))
    {
        @Html.Partial("_AdminMenu")
    }
    else

    {
        @Html.Partial("_MainMenu")
    }
}

<div class="container">
    <table>
        <tr>
            <td style="width:100%"><h3>Edit B&O Tax</h3></td>

        </tr>
    </table>
    <table class="table table-striped">
        <thead class="mdb-color darken-3">
            <tr>

                <th>
                    State <span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> City
                </th>

                <th>
                    Tax
                </th>
                <th>
                    Effective Date

                </th>

            </tr>
        </thead>


        <tr>

            <td>
                @using (Html.BeginForm("BOTax", "Log", FormMethod.Get))
                {

                    @* @Html.DropDownList("type", (IEnumerable<SelectListItem>)ViewBag.lead_type, new { @class = "search_box", onchange = "this.form.submit()" })
                    *@
                    @Html.DropDownList("type", (IEnumerable<SelectListItem>)ViewBag.lead_type, new { @class = "search_box", onchange = "this.form.submit();" })

                    <span> &nbsp;&nbsp;</span> @Html.DropDownList("type1", (IEnumerable<SelectListItem>)ViewBag.lead_type_city, new { @class = "search_box", onchange = "this.form.submit();" })


                }
            </td>




            @if (Model != null)
            {

                foreach (var item in Model)
                {





                    <td>
                        @Html.TextBox("Search", ViewData.TemplateInfo.FormattedModelValue, new { placeholder = @Html.DisplayFor(model => item.tax_value), @class = "search_box" })
                    </td>

                    <td>
                        <input type="date" name="start" class="search_box" />
                    </td>
                    <td>
                        <input type="submit" value="Update" class="btn btn-default" />
                    </td>

                }
            }






        </tr>
        @*  <tr>
                <td>
                    <input type="button" value="Create Lead" onclick="location.href='@Url.Action("ListCustomers", "Customers")'" class="btn btn-default" style="width: 100px;" />
                </td>
            </tr> *@
    </table>



    <table class="table table-striped">
        <thead class="mdb-color darken-3">
            <tr>
                <th> State Name</th>
                <th> City Name</th>
                <th> Tax Value</th>
                <th> Start Date</th>
                <th> End Date </th>
            </tr>

            <tr>
                @if (Model != null)
                {
                    foreach (var item in Model)
                    {
                        <td> @Html.DisplayFor(model => item.state)</td>
                        <td> @Html.DisplayFor(model => item.city)</td>
                        <td> @Html.DisplayFor(model => item.tax_value)</td>
                        <td> @Html.DisplayFor(model => item.start_date)</td>
                        <td> @Html.DisplayFor(model => item.end_date)</td>}
                }
            </tr>
        </thead>
    </table>





    @Html.PagedListPager(Model, page => Url.Action("BOTax",
      new { page, search = Request.QueryString["Search"], Type = Request.QueryString["type"], Start = Request.QueryString["start"], end = Request.QueryString["end"] }), new PagedListRenderOptions() { DisplayPageCountAndCurrentLocation = true })



</div>

27April18-ck-project-Eve/ck-project/Views/Log/CityTax.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<ck_project.tax>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @if (ViewBag.m != null)
    {
        <script type="text/javascript">
 $(document).ready(function () {
     toastr.success('@ViewBag.m');
     @ViewBag.m = null
 });

        </script>
    }
}
@{
    if (HttpContext.Current.User.IsInRole("Administrator"))
    {
        @Html.Partial("_AdminMenu")
    }
    else

    {
        @Html.Partial("_MainMenu")
    }
}

        <div class="container">
            <table>
                <tr>
                    <td style="width:100%"><h3>Edit City Tax</h3></td>

                </tr>
            </table>
            <table class="table table-striped">
                <thead class="mdb-color darken-3">
                    <tr>

                        <th>
                            State <span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> City
                        </th>

                           <th>
            Tax
        </th>
        <th>
            Effective Date

        </th>

                    </tr>
                </thead>


                <tr>

                    <td>
                        @using (Html.BeginForm("CityTax", "Log", FormMethod.Get))
        {

                @* @Html.DropDownList("type", (IEnumerable<SelectListItem>)ViewBag.lead_type, new { @class = "search_box", onchange = "this.form.submit()" })
                *@
                @Html.DropDownList("type", (IEnumerable<SelectListItem>)ViewBag.lead_type, new { @class = "search_box", onchange = "this.form.submit();" })

                <span> &nbsp;&nbsp;</span> @Html.DropDownList("type1", (IEnumerable<SelectListItem>)ViewBag.lead_type_city, new { @class = "search_box", onchange = "this.form.submit();" })


}
                    </td>



                    
                        @if (Model != null)
                {

            foreach (var item in Model)
            {





                <td>
                    @Html.TextBox("Search", ViewData.TemplateInfo.FormattedModelValue, new { placeholder = @Html.DisplayFor(model => item.tax_value), @class = "search_box" })
                </td>

                <td>
                    <input type="date" name="start" class="search_box" />
                </td>
                <td>
                    <input type="submit" value="Update" class="btn btn-default" />
                </td>

        }}






                    </tr>
                    @*  <tr>
                    <td>
                        <input type="button" value="Create Lead" onclick="location.href='@Url.Action("ListCustomers", "Customers")'" class="btn btn-default" style="width: 100px;" />
                    </td>
                </tr> *@
</table>



            <table class="table table-striped">
                <thead class="mdb-color darken-3">
                    <tr>
                        <th> State Name</th>
                        <th> City Name</th>
                        <th> Tax Value</th>
                        <th> Start Date</th>
                        <th> End Date </th>
                    </tr>

                    <tr>
                        @if (Model != null)
                {
                    foreach (var item in Model)
                    {
                        <td> @Html.DisplayFor(model => item.state)</td>
                        <td> @Html.DisplayFor(model => item.city)</td>
                        <td> @Html.DisplayFor(model => item.tax_value)</td>
                        <td> @Html.DisplayFor(model => item.start_date)</td>
                        <td> @Html.DisplayFor(model => item.end_date)</td>}
        }
                    </tr>
                </thead>
            </table>





            @Html.PagedListPager(Model, page => Url.Action("CityTax",
         new { page, search = Request.QueryString["Search"], Type = Request.QueryString["type"], Start = Request.QueryString["start"], end = Request.QueryString["end"] }), new PagedListRenderOptions() { DisplayPageCountAndCurrentLocation = true })



        </div>

27April18-ck-project-Eve/ck-project/Views/Log/CountyTax.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<ck_project.tax>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @if (ViewBag.m != null)
    {
        <script type="text/javascript">
 $(document).ready(function () {
     toastr.success('@ViewBag.m');
     @ViewBag.m = null
 });

        </script>
    }
}
@{
    if (HttpContext.Current.User.IsInRole("Administrator"))
    {
        @Html.Partial("_AdminMenu")
    }
    else

    {
        @Html.Partial("_MainMenu")
    }
}

<div class="container">
    <table>
        <tr>
            <td style="width:100%"><h3>Edit County Tax</h3></td>

        </tr>
    </table>
    <table class="table table-striped">
        <thead class="mdb-color darken-3">
            <tr>

                <th>
                    State <span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> County
                </th>

                <th>
                    Tax
                </th>
                <th>
                    Effective Date

                </th>

            </tr>
        </thead>


        <tr>

            <td>
                @using (Html.BeginForm("CountyTax", "Log", FormMethod.Get))
                {

                    @* @Html.DropDownList("type", (IEnumerable<SelectListItem>)ViewBag.lead_type, new { @class = "search_box", onchange = "this.form.submit()" })
                    *@

                    @Html.DropDownList("type", (IEnumerable<SelectListItem>)ViewBag.lead_type, new { @class = "search_box", onchange = "this.form.submit();" })

                    <span> &nbsp;&nbsp;</span> @Html.DropDownList("type1", (IEnumerable<SelectListItem>)ViewBag.lead_type_county, new { @class = "search_box", onchange = "this.form.submit();" })


                }
            </td>




            @if (Model != null)
            {

                foreach (var item in Model)
                {





                    <td>
                        @Html.TextBox("Search", ViewData.TemplateInfo.FormattedModelValue, new { placeholder = @Html.DisplayFor(model => item.tax_value), @class = "search_box" })
                    </td>

                    <td>
                        <input type="date" name="start" class="search_box" />
                    </td>
                    <td>
                        <input type="submit" value="Update" class="btn btn-default" />
                    </td>

                }
            }






        </tr>
        @*  <tr>
                <td>
                    <input type="button" value="Create Lead" onclick="location.href='@Url.Action("ListCustomers", "Customers")'" class="btn btn-default" style="width: 100px;" />
                </td>
            </tr> *@
    </table>



    <table class="table table-striped">
        <thead class="mdb-color darken-3">
            <tr>
                <th> State Name</th>
                <th> County Name</th>
                <th> Tax Value</th>
                <th> Start Date</th>
                <th> End Date </th>
            </tr>

            <tr>
                @if (Model != null)
                {
                    foreach (var item in Model)
                    {
                        <td> @Html.DisplayFor(model => item.state)</td>
                        <td> @Html.DisplayFor(model => item.county)</td>
                        <td> @Html.DisplayFor(model => item.tax_value)</td>
                        <td> @Html.DisplayFor(model => item.start_date)</td>
                        <td> @Html.DisplayFor(model => item.end_date)</td>}
                }
            </tr>
        </thead>
    </table>





    @Html.PagedListPager(Model, page => Url.Action("CountyTax",
      new { page, search = Request.QueryString["Search"], Type = Request.QueryString["type"], Start = Request.QueryString["start"], end = Request.QueryString["end"] }), new PagedListRenderOptions() { DisplayPageCountAndCurrentLocation = true })



</div>

27April18-ck-project-Eve/ck-project/Views/Log/LaborCost.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<ck_project.rate>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @if (ViewBag.m != null)
    {
        <script type="text/javascript">
 $(document).ready(function () {
     toastr.success('@ViewBag.m');
     @ViewBag.m = null
 });

        </script>
    }
}
@{
    if (HttpContext.Current.User.IsInRole("Administrator"))
    {
        @Html.Partial("_AdminMenu")
    }
    else

    {
        @Html.Partial("_MainMenu")
    }
}

        <div class="container">
            <table>
                <tr>
                    <td style="width:100%"><h3>Edit Labor-Cost</h3></td>

                </tr>
            </table>
            <table class="table table-striped">
                <thead class="mdb-color darken-3">

                    <tr>

                        <th>
                            Rate Name
                        </th>

                             <th>
                        Tax
                    </th>
                    <th>
                        Effective Date

                    </th>

                    </tr>


                    @*<tr>

                    <th>
                        Rate Name
                    </th>

                    <th>
                        Amount
                    </th>
                    <th>
                        Effective Date

                    </th>
                    <th></th>
                </tr>*@
                </thead>


                <tr>

                    <td>
                        @using (Html.BeginForm("LaborCost", "Log", FormMethod.Get))
                {

                    @Html.DropDownList("type", (IEnumerable<SelectListItem>)ViewBag.lead_type, new { @class = "search_box", onchange = "this.form.submit()" })


        }
                    </td>


                    

                @if (Model != null)
                {

                    foreach (var item in Model)
                    {





                <td>

                    @Html.TextBox("Search", ViewData.TemplateInfo.FormattedModelValue, new { placeholder = @Html.DisplayFor(model => item.amount), @class = "search_box" })
                    </td>
                    <td>

                    <input type="date" name="start" class="search_box" />
                   </td>
                    <td>
                        <input type="submit" value="Update" class="btn btn-default" />





                    </td>

                    }
                }




                </tr>
                @*  <tr>
                <td>
                    <input type="button" value="Create Lead" onclick="location.href='@Url.Action("ListCustomers", "Customers")'" class="btn btn-default" style="width: 100px;" />
                </td>
            </tr> *@
            </table>



            <table class="table table-striped">
                <thead class="mdb-color darken-3">
                    <tr>
                        <th> Rate Name</th>
                        
                        <th> Amount</th>
                        <th> Start Date</th>
                        <th> End Date </th>
                    </tr>

                    <tr>
                        @if (Model != null)
                {
                    foreach (var item in Model)
                    {
                        <td> @Html.DisplayFor(model => item.rate_name)</td>
                        <td> @Html.DisplayFor(model => item.amount)</td>
                   
                        <td> @Html.DisplayFor(model => item.start_date)</td>
                        <td> @Html.DisplayFor(model => item.end_date)</td>}
        }
                    </tr>
                </thead>
            </table>





            @Html.PagedListPager(Model, page => Url.Action("LaborCost",
             new { page, search = Request.QueryString["Search"], Type = Request.QueryString["type"], Start = Request.QueryString["start"], end = Request.QueryString["end"] }), new PagedListRenderOptions() { DisplayPageCountAndCurrentLocation = true })



        </div>

27April18-ck-project-Eve/ck-project/Views/Log/ListLog.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<ck_project.lead_log_file>


@Html.Partial("_AdminMenu")

<div class="container">
    <table>
        <tr>
            <td style="width:435px"><h2>Leads Logs</h2></td>
            <td style="width:680px" align="right"></td>
        </tr>
        <tr>

            <td>This page displays all updates on leads.</td>
            <td rowspan="2">
                @using (Html.BeginForm("ListLog", "Log", FormMethod.Get))
                {
                    <b>Project Name: </b>
                    @Html.TextBox("Search", ViewData.TemplateInfo.FormattedModelValue, new { placeholder = "Type project name here", @class = "search_box" });
                    <b>&nbsp;&nbsp;&nbsp;&nbsp;Salesperson:</b>
                    @Html.DropDownList("Emp", (IEnumerable<SelectListItem>)ViewBag.EmpInfo, new { @class = "search_box" });
                    <div style="float:left; padding-top:12px"><b>&nbsp;&nbsp;&nbsp;Update Date:&nbsp;</b></div>
                    <div style="float:left; padding-right:10px; padding-top:4px"><input style="width:160px;" type="date" name="start" class="search_box" /></div>
                    <div style="float:left; padding-right:20px; padding-top:4px"><input style="width:160px" type="date" name="end" class="search_box" /></div>
                    <div style="padding-top:6px"><input type="submit" value="Search" class="btn btn-default" /></div>
                }
            </td>
        </tr>

    </table>
    <div style="padding-top:15px"></div>

    <table class="table table-striped">
        <thead class="mdb-color darken-3">

            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.First().lead.project_name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.First().emp_username)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.First().table_name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.First().column_name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.First().action_name)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.First().prvious_value)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.First().new_value)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.First().update_date)
                </th>

                <th></th>
            </tr>
        </thead>
        @if (Model != null)
        {
            foreach (var item in Model)
            {
                <tr>
                    <td>

                        @Html.DisplayFor(modelItem => item.lead.project_name)
                    </td>
                    <td>

                        @Html.DisplayFor(modelItem => item.emp_username)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.table_name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.column_name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.action_name)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.prvious_value)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.new_value)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.update_date)
                    </td>


                </tr>
            }
        }
    </table>

    @Html.PagedListPager(Model, page => Url.Action("ListLog", new { page, search = Request.QueryString["Search"], Emp = Request.QueryString["Emp"], Start = Request.QueryString["start"], end = Request.QueryString["end"] }), new PagedListRenderOptions() { DisplayPageCountAndCurrentLocation = true })

</div>