27April18-ck-project-Eve/ck-project/Controllers/LeadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;
using Microsoft.AspNet.Identity;
using ck_project.Helpers;



namespace ck_project.Controllers
{
    [Authorize]

    public class LeadController : Controller
    {
        //Creating the DB connecton
        ckdatabase db = new ckdatabase();
        static List<lead> lst = new List<lead>();

        // GET: Lead




        public ActionResult ListLead(int? page, string search = null, string Type = null, string Start = null, string end = null, string msg = null)
        {

            int type = string.IsNullOrEmpty(Type) ? 3 : int.Parse(Type);
            DateTime start = string.IsNullOrEmpty(Start) ? DateTime.MinValue : DateTime.Parse(Start);
            DateTime end2 = string.IsNullOrEmpty(end) ? DateTime.MaxValue : DateTime.Parse(end);
            TimeSpan ts = new TimeSpan(23, 59, 59);
            end2 = end2.Date + ts;

            int statusNbr = 0;
            if (!string.IsNullOrEmpty(Type))
            {
                statusNbr = Int32.Parse(Type);
            }

            try
            {
                ViewBag.m = msg;
                var ClassInfo = new List<SelectListItem> {
                    new SelectListItem() { Text = "All", Selected = true, Value = "" }
                };
                ClassInfo.AddRange(db.project_status.Where(CCVV => CCVV.project_status_name != "closed").Select(b => new SelectListItem

                {
                    Text = b.project_status_name,
                    Selected = false,
                    Value = b.project_status_number.ToString()
                }));
                ViewBag.lead_type = ClassInfo;
                var result = db.leads.Where(l => (l.project_status_number != 6 && l.deleted == false)
                                      && l.lead_date >= start && l.lead_date <= end2
                                      && (string.IsNullOrEmpty(Type) || l.project_status_number == statusNbr)
                                      && (string.IsNullOrEmpty(search) || l.project_name.Contains(search))).ToList();


                LeadController.lst = result;
                return View(result.ToPagedList(page ?? 1, 8));

                //return View(db.leads.Where(x => (x.project_name.Contains(search) || search == null) && x.project_status_number == type && (x.project_status_number != 6 && x.deleted == false)).ToList());
            }
            catch (Exception e)
            {
                ViewBag.m = "Something went wrong ... " + e.Message;
                return View();
            }
        }


        public ActionResult Add(int id, String msg = null, string add = null)
        {
            ViewBag.add = add;
            ViewBag.m = msg;
            try
            {
                List<SelectListItem> CustomerInfo = new List<SelectListItem>();
                CustomerInfo.AddRange(db.customers.Where(x => x.deleted != true).Select(a => new SelectListItem
                {
                    Text = a.customer_lastname,
                    Selected = false,
                    Value = a.customer_number.ToString()
                }));

                var ClassInfo = new List<SelectListItem>();
                ClassInfo.AddRange(db.project_class.Where(x => x.deleted != true).Select(b => new SelectListItem
                {
                    Text = b.class_name,
                    Selected = false,
                    Value = b.class_number.ToString()
                }));

                var StatusInfo = new List<SelectListItem>();
                StatusInfo.AddRange(db.project_status.Where(x => x.deleted != true).Select(c => new SelectListItem
                {
                    Text = c.project_status_name,
                    Selected = false,
                    Value = c.project_status_number.ToString()
                }));

                var ProjectTypeInfo = new List<SelectListItem>();
                ProjectTypeInfo.AddRange(db.project_type.Where(x => x.deleted != true).Select(b => new SelectListItem
                {
                    Text = b.project_type_name,
                    Selected = false,
                    Value = b.project_type_number.ToString()
                }));

                var SourceInfo = new List<SelectListItem>();
                SourceInfo.AddRange(db.lead_source.Where(x => x.deleted != true).Select(b => new SelectListItem
                {
                    Text = b.source_name,
                    Selected = false,
                    Value = b.source_number.ToString()
                }));

                var AddressInfo = new List<SelectListItem>();
                AddressInfo.AddRange(db.addresses.Where(x => x.deleted != true).Select(a => new SelectListItem
                {
                    Text = a.address_type,
                    Selected = false,
                    Value = a.address_number.ToString()
                }));

                //    var AddressCityInfo = new List<SelectListItem>();

                var EmpInfo = new List<SelectListItem>();
                EmpInfo.AddRange(db.employees.Where(x => x.deleted != true).Select(a => new SelectListItem
                {
                    Text = a.emp_firstname + " " + a.emp_lastname,
                    Selected = false,
                    Value = a.emp_number.ToString()
                }));

                var BranchInfo = new List<SelectListItem>();
                BranchInfo.AddRange(db.branches.Where(x => x.deleted != true).Select(a => new SelectListItem
                {
                    Text = a.branch_name,
                    Selected = false,
                    Value = a.branch_number.ToString()
                }));

                var DeliveryStatusInfo = new List<SelectListItem>();
                DeliveryStatusInfo.AddRange(db.delivery_status.Select(a => new SelectListItem
                {
                    Text = a.delivery_status_name,
                    Selected = false,
                    Value = a.delivery_status_number.ToString()
                }));

                var TaxExemptInfo = new List<SelectListItem> {


                  new SelectListItem() { Text = "Taxable", Value = "0" },
                new SelectListItem { Text = "Tax Exempt", Value = "1" }
            };

                ViewBag.TaxExemptInfo = TaxExemptInfo;
                //setting variable passing
                ViewBag.Customer_Info = CustomerInfo;
                ViewBag.Class_Info = ClassInfo;
                ViewBag.Status_Info = StatusInfo;
                ViewBag.ProjectType_Info = ProjectTypeInfo;
                ViewBag.Source_Info = SourceInfo;
                ViewBag.Address_Info = AddressInfo;
                ViewBag.Emp_Info = EmpInfo;
                ViewBag.Branch_Info = BranchInfo;
                ViewBag.DeliveryStatus_Info = DeliveryStatusInfo;

                var Sstate = new List<SelectListItem> {
               new SelectListItem() {Text="Alabama", Value="AL"},
        new SelectListItem() { Text="Alaska", Value="AK"},
        new SelectListItem() { Text="Arizona", Value="AZ"},
        new SelectListItem() { Text="Arkansas", Value="AR"},
        new SelectListItem() { Text="California", Value="CA"},
        new SelectListItem() { Text="Colorado", Value="CO"},
        new SelectListItem() { Text="Connecticut", Value="CT"},
        new SelectListItem() { Text="District of Columbia", Value="DC"},
        new SelectListItem() { Text="Delaware", Value="DE"},
        new SelectListItem() { Text="Florida", Value="FL"},
        new SelectListItem() { Text="Georgia", Value="GA"},
        new SelectListItem() { Text="Hawaii", Value="HI"},
        new SelectListItem() { Text="Idaho", Value="ID"},
        new SelectListItem() { Text="Illinois", Value="IL"},
        new SelectListItem() { Text="Indiana", Value="IN"},
        new SelectListItem() { Text="Iowa", Value="IA"},
        new SelectListItem() { Text="Kansas", Value="KS"},
        new SelectListItem() { Text="Kentucky", Value="KY"},
        new SelectListItem() { Text="Louisiana", Value="LA"},
        new SelectListItem() { Text="Maine", Value="ME"},
        new SelectListItem() { Text="Maryland", Value="MD"},
        new SelectListItem() { Text="Massachusetts", Value="MA"},
        new SelectListItem() { Text="Michigan", Value="MI"},
        new SelectListItem() { Text="Minnesota", Value="MN"},
        new SelectListItem() { Text="Mississippi", Value="MS"},
        new SelectListItem() { Text="Missouri", Value="MO"},
        new SelectListItem() { Text="Montana", Value="MT"},
        new SelectListItem() { Text="Nebraska", Value="NE"},
        new SelectListItem() { Text="Nevada", Value="NV"},
        new SelectListItem() { Text="New Hampshire", Value="NH"},
        new SelectListItem() { Text="New Jersey", Value="NJ"},
        new SelectListItem() { Text="New Mexico", Value="NM"},
        new SelectListItem() { Text="New York", Value="NY"},
        new SelectListItem() { Text="North Carolina", Value="NC"},
        new SelectListItem() { Text="North Dakota", Value="ND"},
        new SelectListItem() { Text="Ohio", Value="OH"},
        new SelectListItem() { Text="Oklahoma", Value="OK"},
        new SelectListItem() { Text="Oregon", Value="OR"},
        new SelectListItem() { Text="Pennsylvania", Value="PA"},
        new SelectListItem() { Text="Rhode Island", Value="RI"},
        new SelectListItem() { Text="South Carolina", Value="SC"},
        new SelectListItem() { Text="South Dakota", Value="SD"},
        new SelectListItem() { Text="Tennessee", Value="TN"},
        new SelectListItem() { Text="Texas", Value="TX"},
        new SelectListItem() { Text="Utah", Value="UT"},
        new SelectListItem() { Text="Vermont", Value="VT"},
        new SelectListItem() { Text="Virginia", Value="VA"},
        new SelectListItem() { Text="Washington", Value="WA"},

27April18-ck-project-Eve/ck-project/Views/Lead/Edit.cshtml
@model ck_project.lead

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @if (ViewBag.m != null)
    {
        <script type="text/javascript">
 $(document).ready(function () {
     toastr.success('@ViewBag.m');
    
});
        </script>
    }
}

@{
    <link href="~/Content/Tabs.css" rel="stylesheet" type="text/css" />
    if (HttpContext.Current.User.IsInRole("Administrator"))
    {
        @Html.Partial("_AdminMenu")
    }
    else
    {
        @Html.Partial("_MainMenu")
    }
}

<div class="container">


    <table>
        <tr>
            <td style="width:1150px"><h3>Edit Lead</h3></td>
            <td style="width:50px">
            </td>
        </tr>
    </table>
    <div style="padding-bottom:10px"></div>




    <table>
        <tr>
            <td style="width:50px" align="right">
            </td>
        </tr>
        <tr>
            <td style="width:947px"><h5>All the fields with star are required</h5></td>
            <td style="width:50px">
                <input type="button" value="Customer" onclick="location.href='@Url.Action("Edit", "Customers", new { id = @Model.customer_number })'" class="btn btn-default" id="tabBtn" />
            </td>
            <td style="width:50px">
                <input type="button" value="Products" onclick="location.href='@Url.Action("View", "Product", new { id = @Model.lead_number })'" class="btn btn-default" id="tabBtn" />
            </td>
            <td style="width:100px">
                <input type="button" value="Installation" onclick="location.href='@Url.Action("Lis", "Install", new { lid = @Model.lead_number })'" class="btn btn-default" id="tabBtn" />
            </td>
            <td style="width:50px">
                <input type="button" value="Summary" onclick="location.href='@Url.Action("ProjSummary", "Home", new { id = @Model.lead_number })'" class="btn btn-default" id="tabBtn" />
            </td>
            <td style="width:50px">
                <input type="button" value="Print" onclick="location.href='@Url.Action("ProjPrint", "Home", new { id = @Model.lead_number })'" class="btn btn-default" id="tabBtn" />
            </td>
        </tr>
    </table>
    <hr />
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.lead_number)
            <div class='col-xs-4 '>
                <label class='control-label'>Project Name*</label>
                @Html.EditorFor(model => model.project_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.project_name, "", new { @class = "text-danger" })
            </div>
            <div class='col-xs-4 '>
                <label class='control-label'>CLass Name*</label>
                @Html.DropDownList("class_number", (List<SelectListItem>)ViewBag.Class_Info, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.class_number, "", new { @class = "text-danger" })
            </div>

            <div class='col-xs-4 '>
                <label class='control-label'>Project Status*</label>
                @Html.DropDownList("project_status_number", (IEnumerable<SelectListItem>)ViewBag.Status_Info, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.project_status_number, "", new { @class = "text-danger" })
            </div>
            <div class='col-xs-4 '>
                <label class='control-label'>Project Type*</label>
                @Html.DropDownList("project_type_number", (IEnumerable<SelectListItem>)ViewBag.ProjectType_Info, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.project_type_number, "", new { @class = "text-danger" })
            </div>
            <div class='col-xs-4 '>
                <label class='control-label'>Project Source*</label>
                @Html.DropDownList("source_number", (IEnumerable<SelectListItem>)ViewBag.Source_Info, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.source_number, "", new { @class = "text-danger" })
            </div>
            <div class='col-xs-4 '>
                <label class='control-label'>Designer Name*</label>
                @Html.DropDownList("emp_number", (IEnumerable<SelectListItem>)ViewBag.Emp_Info, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.emp_number, "", new { @class = "text-danger" })
            </div>
            <div class='col-xs-4 '>
                <label class='control-label'>Branch Name*</label>
                @Html.DropDownList("branch_number", (IEnumerable<SelectListItem>)ViewBag.Branch_Info, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.branch_number, "", new { @class = "text-danger" })
            </div>
            <div class='col-xs-4 '>
                <label class='control-label'>Delivery Status*</label>
                @Html.DropDownList("delivery_status_number", (IEnumerable<SelectListItem>)ViewBag.DeliveryStatus_Info, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.delivery_status_number, "", new { @class = "text-danger" })
            </div>

            <div class='col-xs-4'>

                    <label class='control-label'>Tax Exempt*</label>
                    @Html.DropDownList("tax_exempt", (IEnumerable<SelectListItem>)ViewBag.TaxExemptInfo, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.tax_exempt, "", new { @class = "text-danger" })
       
            </div>

            <div class='col-xs-4 '>
                <label class="control-label" for="name">Phone Number</label>
                @Html.EditorFor(model => model.phone_number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.phone_number, "", new { @class = "text-danger" })
            </div>
            <div class='col-xs-4 '>
                <label class="control-label" for="name">Phone Number2</label>
                @Html.EditorFor(model => model.second_phone_number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.second_phone_number, "", new { @class = "text-danger" })
            </div>
            <div class='col-xs-4 '>
                <label class="control-label" for="name"> Email Address</label>
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>

            <div class='col-xs-4 '>
  
                    <label class="control-label" for="name"> Note</label>
                    @Html.EditorFor(model => model.note, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.note, "", new { @class = "text-danger" })

            </div>

            <div class='col-xs-4 '>
                <label class='control-label'>In City? </label>
                @Html.EditorFor(model => model.in_city)
                @Html.ValidationMessageFor(model => model.in_city, "", new { @class = "text-danger" })
            </div>


            @*<div class='col-xs-4 '>
                <label class='control-label'>Tax Exempt? </label>
                @Html.EditorFor(model => model.tax_exempt)
                @Html.ValidationMessageFor(model => model.tax_exempt, "", new { @class = "text-danger" })
            </div>*@
         
            <div class="form-group">
                <div class="col-md-offset-0 col-md-10">
                    <br>
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    <div>
        @Html.ActionLink("Edit address info", "Edit", "Address", new { id = ViewBag.addressnumber,mode="l" }, new { @class = "btn btn-default", @style = "width: 140px" })
    </div>
    <div>
        @Html.ActionLink("Back to List", "ListLead")
    </div>
</div>

27April18-ck-project-Eve/ck-project/Views/Lead/ListLead.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<ck_project.lead>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @if (ViewBag.m != null)
    {
        <script type="text/javascript">
 $(document).ready(function () {
     toastr.success('@ViewBag.m');
     @ViewBag.m = null
 });

        </script>
    }
}
@{
    if (HttpContext.Current.User.IsInRole("Administrator"))
    {
        @Html.Partial("_AdminMenu")
    }
    else

    {
        @Html.Partial("_MainMenu")
    }
}

<div class="container">
    <table>
        <tr>
            <td style="width:720px"><h3>Projects</h3></td>
            <td style="width:700px" align="right"></td>
        </tr>
        <tr>
            <td>This page displays all leads.</td>
            <td rowspan="2">
                @using (Html.BeginForm("ListLead", "Lead", FormMethod.Get))
                {
                    <b>Project Name: </b>
                    @Html.TextBox("Search", ViewData.TemplateInfo.FormattedModelValue, new { placeholder = "Type project name here", @class = "search_box" });
                    <b>&nbsp;&nbsp;&nbsp;&nbsp;Status:</b>
                    @Html.DropDownList("type", (IEnumerable<SelectListItem>)ViewBag.lead_type, new { @class = "search_box" });
                    <div style="float:left; padding-top:12px"><b>&nbsp;&nbsp;&nbsp;Create Date:&nbsp;</b></div>
                    <div style="float:left; padding-right:10px; padding-top:4px"><input style="width:160px;" type="date" name="start" class="search_box" /></div>
                    <div style="float:left; padding-right:20px; padding-top:4px"><input style="width:160px" type="date" name="end" class="search_box" /></div>
                    <div style="padding-top:6px"><input type="submit" value="Search" class="btn btn-default" /></div>
                }
            </td>
        </tr>
        @*  <tr>
                <td>
                    <input type="button" value="Create Lead" onclick="location.href='@Url.Action("ListCustomers", "Customers")'" class="btn btn-default" style="width: 100px;" />
                </td>
            </tr> *@
    </table>
    <div style="padding-top:15px"></div>
    <table class="table table-striped">
        <thead class="mdb-color darken-3">
            <tr>
                <th>
                    @Html.ActionLink("Customer Name", "Sort", new { by = "cn" })
                </th>
                <th>
                    @Html.ActionLink("Project Name", "Sort", new { by = "pn" })
                </th>

                <th>
                    @Html.ActionLink("Designer", "Sort", new { by = "ds" })
                </th>
                <th>
                    @Html.ActionLink("SalesPerson", "Sort", new { by = "sp" })
                </th>
                <th>
                    @Html.ActionLink("Project Type", "Sort", new { by = "pt" })
                </th>
                <th>
                    @Html.ActionLink("Project Status", "Sort", new { by = "ps" })
                </th>
                <th>
                    @Html.ActionLink("Create Dated", "Sort", new { by = "cd" })
                </th>
                <th>
                    @Html.ActionLink("Last Update Date", "Sort", new { by = "lud" })
                </th>
                <th>
                    @Html.ActionLink("Branch", "Sort", new { by = "br" })
                </th>
                <th></th>
            </tr>
        </thead>
        @if (Model != null)
        {
            @*@if (Model.Count() == 0)
                {
                    <tr>
                        <td colspan="6"> Sorry, There are no leads with the entered project name
                        <td>
                    </tr>
                }
                else
                {*@
            foreach (var item in Model)
            {


        <tr>

            <td>
                @Html.DisplayFor(model => item.customer.customer_firstname)
                @Html.DisplayFor(model => item.customer.customer_lastname)
            </td>
            <td>
                @Html.DisplayFor(model => item.project_name)
            </td>
            <td>
                @Html.DisplayFor(model => item.employee.emp_firstname)
                @Html.DisplayFor(model => item.employee.emp_lastname)
            </td>
            <td>
                @Html.DisplayFor(model => item.lead_creator)
            </td>
            <td>
                @Html.DisplayFor(model => item.project_type.project_type_name)
            </td>
            <td>
                @Html.DisplayFor(model => item.project_status.project_status_name)
            </td>
            <td>
                @*@Html.DisplayFor(model => Model.First().lead_date)*@
                @item.lead_date.ToString("dd MMM yyyy")
            </td>
            <td>
                @{
            if (item.Last_update_date == item.lead_date)
            {
                @Html.DisplayName(" - ")
    }
    else
    {
        @Html.DisplayName(item.Last_update_date.ToString("dd MMM yyyy"))
} }
            </td>
            <td>
                @Html.DisplayFor(model => item.branch.branch_name)
            </td>

            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.lead_number }) |
                @Html.ActionLink("Details", "ProjSummary", "Home", new { id = item.lead_number }, null) |
                @Html.ActionLink("Delete", "Delete", new { id = item.lead_number },
                           new { onclick = "return confirm('Are you sure you wish to delete the lead?');" })
            </td>
        </tr>
            }
        }
    </table>
    @Html.PagedListPager(Model, page => Url.Action("ListLead",
        new { page, search = Request.QueryString["Search"], Type = Request.QueryString["type"], Start = Request.QueryString["start"], end = Request.QueryString["end"] }), new PagedListRenderOptions() { DisplayPageCountAndCurrentLocation = true })



</div>